// This object maps currency codes (e.g. USD) to country codes (e.g. US)
// It's used to display country flags using a flag API (e.g., https://flagsapi.com)
// let currency = "USD";
// let countryCode = countrylist[currency]; // "US"
// let flagURL = `https://flagsapi.com/${countryCode}/flat/64.png`;


const countrylist = {
    AED: "AE", // United Arab Emirates Dirham → AE (UAE)
    ARS: "AR", // Argentine Peso → AR (Argentina)
    AUD: "AU", // Australian Dollar → AU (Australia)
    BDT: "BD", // Bangladeshi Taka → BD (Bangladesh)
    BGN: "BG", // Bulgarian Lev → BG (Bulgaria)
    BRL: "BR", // Brazilian Real → BR (Brazil)
    CAD: "CA", // Canadian Dollar → CA (Canada)
    CHF: "CH", // Swiss Franc → CH (Switzerland)
    CLP: "CL", // Chilean Peso → CL (Chile)
    CNY: "CN", // Chinese Yuan → CN (China)
    COP: "CO", // Colombian Peso → CO (Colombia)
    CZK: "CZ", // Czech Koruna → CZ (Czech Republic)
    DKK: "DK", // Danish Krone → DK (Denmark)
    DOP: "DO", // Dominican Peso → DO (Dominican Republic)
    EGP: "EG", // Egyptian Pound → EG (Egypt)
    EUR: "EU", // Euro → EU (European Union)
    GBP: "GB", // British Pound → GB (United Kingdom)
    GHS: "GH", // Ghanaian Cedi → GH (Ghana)
    HKD: "HK", // Hong Kong Dollar → HK (Hong Kong)
    HUF: "HU", // Hungarian Forint → HU (Hungary)
    IDR: "ID", // Indonesian Rupiah → ID (Indonesia)
    ILS: "IL", // Israeli Shekel → IL (Israel)
    INR: "IN", // Indian Rupee → IN (India)
    JPY: "JP", // Japanese Yen → JP (Japan)
    KRW: "KR", // South Korean Won → KR (South Korea)
    KZT: "KZ", // Kazakhstani Tenge → KZ (Kazakhstan)
    LKR: "LK", // Sri Lankan Rupee → LK (Sri Lanka)
    MAD: "MA", // Moroccan Dirham → MA (Morocco)
    MXN: "MX", // Mexican Peso → MX (Mexico)
    MYR: "MY", // Malaysian Ringgit → MY (Malaysia)
    NGN: "NG", // Nigerian Naira → NG (Nigeria)
    NOK: "NO", // Norwegian Krone → NO (Norway)
    NZD: "NZ", // New Zealand Dollar → NZ (New Zealand)
    PKR: "PK", // Pakistani Rupee → PK (Pakistan)
    PHP: "PH", // Philippine Peso → PH (Philippines)
    PLN: "PL", // Polish Zloty → PL (Poland)
    QAR: "QA", // Qatari Riyal → QA (Qatar)
    RON: "RO", // Romanian Leu → RO (Romania)
    RUB: "RU", // Russian Ruble → RU (Russia)
    SAR: "SA", // Saudi Riyal → SA (Saudi Arabia)
    SEK: "SE", // Swedish Krona → SE (Sweden)
    SGD: "SG", // Singapore Dollar → SG (Singapore)
    THB: "TH", // Thai Baht → TH (Thailand)
    TRY: "TR", // Turkish Lira → TR (Turkey)
    TWD: "TW", // Taiwan Dollar → TW (Taiwan)
    UAH: "UA", // Ukrainian Hryvnia → UA (Ukraine)
    USD: "US", // US Dollar → US (United States)
    VND: "VN", // Vietnamese Dong → VN (Vietnam)
    ZAR: "ZA"  // South African Rand → ZA (South Africa)
};
